# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "KPSHTM"

# A description of your site for meta tag, search engine results.
description: "Scriptor is a minimal, clean, modern & responsive Jekyll theme for writers"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: kpshtm.github.io

# Change the destination output to ./docs as based gh-pages
destination: ./docs

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-D024BXJQHQ"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Journal
    url: /journal
  - text: About
    url: /about
  - text: Track
    url: /track
  - text: Reading
    url: /reading

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#fabd2f'

# Site footer
footer:
  content: "&copy; themes based on Scriptor all rights reserved. Modified by needed."
  has_social: true

# Plugins
# plugins:
#   - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
# paginate: 3
# paginate_path: '/page:num/'

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: journal
      read_time: true
  # - scope:
  #     path: "tracks"
  #     type: posts
  #   values:
  #     layout: tracks
  #     extname: .gpx

# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Compress
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]
